# Generated by Django 5.0.4 on 2024-04-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('question_id', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('question_category', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('answer_text', models.CharField(default='No answer provided', max_length=200)),
                ('answer_category', models.CharField(blank=True, max_length=30, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.question')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('score_value', models.FloatField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.question')),
            ],
        ),
    ]
